# Site settings
title: Spreadsheet Help
tagline: 
email: uc3@ucop.edu
description: ""
baseurl: "http://CDLUC3.github.io/spreadsheet-help"
url: "http://www.cdlib.org"
twitter_username: UC3CDL
github_username:  CDLUC3

# Build settings
markdown: redcarpet
permalink: pretty
pygments: true
